name: Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-actions@${{ secrets.GKE_PROJECT }}.iam.gserviceaccount.com'
    
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
    
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build Docker Image
      run: docker build -t gcr.io/${{ secrets.GKE_PROJECT }}/my-website:${{ github.sha }} .
    
    - name: Push to Google Container Registry
      run: docker push gcr.io/${{ secrets.GKE_PROJECT }}/my-website:${{ github.sha }}
    
    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials my-cluster --zone my-zone
        kubectl set image deployment/my-deployment my-container=gcr.io/${{ secrets.GKE_PROJECT }}/my-website:${{ github.sha }}
