name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Authenticate Docker with Google Container Registry
      - name: Authenticate Docker with GCR
        run: |
          echo ${{ secrets.GCP_CREDENTIALS }} | docker login -u _json_key --password-stdin https://gcr.io

      # Step 4: Build and push the Docker image to Google Container Registry
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:latest

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-service-name \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
