name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: my-cluster
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: website-deployment
  IMAGE: my-website

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Google Cloud Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Install GKE gcloud auth plugin
      run: |
        # Download the auth plugin
        curl -Lo gke-gcloud-auth-plugin-linux-amd64.tar.gz https://dl.google.com/cloudsdk/gke-gcloud-auth-plugin-linux-amd64.tar.gz

        # Verify if the file exists
        if [ ! -f "gke-gcloud-auth-plugin-linux-amd64.tar.gz" ]; then
          echo "File not found!"
          exit 1
        fi

        # Extract the tar file
        tar -xvzf gke-gcloud-auth-plugin-linux-amd64.tar.gz

        # Move the plugin to /usr/local/bin/
        sudo mv gke-gcloud-auth-plugin /usr/local/bin/

    - name: Configure Docker Auth
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:${{ github.sha }} .

    - name: Push to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
        kubectl set image deployment/$DEPLOYMENT_NAME $IMAGE=us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:${{ github.sha }}
